### PR TITLE
https://ontouchstart.github.io/neurojs/examples/cars/touch.html

### PR DESCRIPTION
**Pull request by ghost**
A quick and dirty fix to add touch event to the cars demo.

### CODE REVIEW

**Comment by beescuit** [comment]
Idk if the drawing of the obstacles was supposed to fill when the finish of the path isn't close to the start... But I think that even on a desktop it feels better to draw it.

**Comment by ghost** [comment]
@BeeCodiing It is a hit-and-miss. Following screenshots were taken on iPad Pro 9.7 drawn with finger as well as Apple pencil.

img_0992
img_0993
img_0994

**Comment by janhuenermann** [comment]
This is cool, especially when running on a tablet. But I think it may be better (and cleaner) to just add the touch functionality to the existing page, and not to a separate page (single file for desktop and mobile). This could be done by binding the events in the `renderer.js`.

**Comment by ghost** [comment]
You can definitely do it that way as long as there is no unintended side effect. Since I am not familiar with the codebase, I want to play it safe.

**Pull request closed without merging**
